name: builds
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  nix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-21.04
      - run: nix-build -A nrm-python
