name: nrm-install-checks
on:
  push:
    branches:
      - master
  pull_request:

jobs:
    check-pip-install:
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: bash -l {0}

        steps:
        - uses: actions/checkout@v2
        - name: Setup conda
          uses: conda-incubator/setup-miniconda@v2
          with:
            activate-environment: condaenv
            miniconda-version: "latest"
            python-version: 3.8
            channels: conda-forge
            channel-priority: flexible
            auto-update-conda: true

        - name: Install check
          if: matrix.check == 'install'
          run: |
            pip install -e .
