name: nrm-install-checks
on:
  push:
    branches:
      - master
  pull_request:

jobs:
    check-pip-install:
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: bash -l {0}

        env:
            PATH: $PWD/nrm-core-master/bin:$PATH
            LD_LIBRARY_PATH: $PWD/nrm-core-master/lib:$LD_LIBRARY_PATH

        steps:
        - uses: actions/checkout@v2
        - name: Setup conda
          uses: conda-incubator/setup-miniconda@v2
          with:
            activate-environment: condaenv
            miniconda-version: "latest"
            python-version: 3.8
            channels: conda-forge
            channel-priority: flexible
            auto-update-conda: true

        - name: Install nrm-core release
          run: |
           wget https://github.com/anlsys/nrm-core/releases/download/master-build/nrm-core-master.tar.gz
           mkdir ./nrm-core-master; tar xvf nrm-core-master.tar.gz -C ./nrm-core-master

        - name: Pip install check
          run: pip install -e .
